### ISSUE TITLE
touch-action property isn't recognized

### ISSUE THREAD

**Issue by cvrebert** [MarioRicalde/SCSS.tmbundle#199]
Example:

``` scss
.foo {
  touch-action: manipulation;
}
```

Docs regarding the property:
- https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action
- https://www.w3.org/TR/pointerevents/#the-touch-action-css-property
- https://w3c.github.io/pointerevents/#the-touch-action-css-property
