### ISSUE TITLE
Attribute selector sometimes highlighted as syntax error

### ISSUE THREAD

**Issue by cvrebert** [MarioRicalde/SCSS.tmbundle#201]
Example:

``` scss
@mixin label-variant($color) {
  &[href] {
    background-color: $color;
  }
}
```
